// One-off: vendor the Google Fonts faces used by index.html into
// client/public/fonts/ + emit client/public/fonts/fonts.css (@font-face rules
// pointing at the local files). Run from repo root: `node scripts/vendor-fonts.mjs`.
// Keeps only the latin + latin-ext subsets — the app is English-only (manifest
// lang "en"). Re-run if the font list in index.html changes.

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'client/public/fonts')

// Same query as the <link> in client/index.html.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Figtree:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap'
// A modern desktop Chrome UA so Google serves woff2 (not ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])
const slug = (s) => s.toLowerCase().replace(/\s+/g, '-')

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// css2 emits: /* subset */ then a @font-face { font-family; font-weight; src: url(x) format('woff2'); unicode-range }
const blocks = css.split('@font-face').slice(1)
let subset = 'latin'
const out = []
const subsetComments = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\//g)].map((m) => m[1])
let ci = 0

for (const raw of blocks) {
  // the subset comment immediately precedes each @font-face in source order
  subset = subsetComments[ci++] ?? subset
  const family = raw.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = raw.match(/font-weight:\s*(\d+)/)?.[1]
  const url = raw.match(/src:\s*url\(([^)]+)\)/)?.[1]
  const range = raw.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
  if (!family || !weight || !url || !KEEP_SUBSETS.has(subset)) continue

  const fname = `${slug(family)}-${weight}-${subset}.woff2`
  const bin = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  await mkdir(outDir, { recursive: true })
  await writeFile(resolve(outDir, fname), bin)
  console.log('wrote', `client/public/fonts/${fname}`, bin.length, 'bytes')

  out.push(
    `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${fname}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}`,
  )
}

await writeFile(
  resolve(outDir, 'fonts.css'),
  `/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n\n${out.join('\n\n')}\n`,
)
console.log('wrote client/public/fonts/fonts.css —', out.length, 'faces')
